spring.application.name=onboarding-api

spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:32002/railway
spring.datasource.username=postgres
spring.datasource.password=eoUcBNdPrhzLkjTrfsAfyYrHfDKTrEwy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
